from __future__ import annotations

from .capabilities import PROVENANCE
from .registry import CuratedEvidence, ThreatScenario

_SCENARIOS = (
    ("TS-101", "Unauthorized inbound service access", "network-adjacent attacker", "a listening service is reachable", "host services", "missing default-deny filtering", "connects to an unintended service", "obtain an initial foothold", "unauthorized network access", "service exploitation or unauthorized access", ("BND-NETWORK-HOST-FIREWALL",), ("TEC-004",)),
    ("TS-102", "Lateral movement through administrative protocols", "attacker on an internal host", "administrative protocols are reachable", "managed hosts", "weakly restricted administrative paths", "authenticates to or exploits a management service", "move to another host", "unauthorized administrative session", "lateral movement", ("BND-NETWORK-SMB-SESSION", "BND-REMOTE-WINRM", "BND-REMOTE-RDP"), ("TEC-003",)),
    ("TS-103", "SMB authentication relay", "attacker able to intercept network authentication", "an SMB endpoint accepts relayed or unsigned authentication", "file services and identities", "missing SMB session integrity", "relays authentication to SMB", "impersonate the victim", "unauthorized SMB authentication", "resource access under the victim identity", ("BND-NETWORK-SMB-SESSION",), ("TEC-001", "TEC-002")),
    ("TS-104", "LDAP authentication relay", "attacker able to intercept directory authentication", "a directory endpoint accepts an unprotected bind", "directory services and identities", "missing LDAP signing or channel protection", "relays authentication to the directory service", "act with the victim's directory privileges", "unauthorized directory access", "privilege escalation or directory modification", ("BND-IDENTITY-LDAP-CHANNEL",), ("TEC-001", "TEC-002")),
    ("TS-105", "Authentication downgrade to weak NTLM behavior", "network-adjacent attacker or malicious service", "legacy negotiation remains accepted", "identities and authenticating services", "weak authentication fallback", "forces weaker authentication negotiation", "capture or relay reusable authentication", "weak authentication accepted", "identity impersonation", ("BND-IDENTITY-NTLM-SESSION",), ("TEC-005", "TEC-001")),
    ("TS-106", "Weak NTLM session integrity or confidentiality", "attacker on the communication path", "a session lacks required integrity or encryption", "authenticated sessions", "weak session security", "observes or alters protected session data", "steal or manipulate session content", "session confidentiality or integrity lost", "credential or data exposure", ("BND-IDENTITY-NTLM-SESSION",), ("TEC-002",)),
    ("TS-107", "Interception of remote-management traffic", "attacker on a management network path", "management traffic permits weak or plaintext transport", "management sessions and credentials", "missing channel cryptography", "intercepts or modifies management traffic", "capture credentials or commands", "management channel compromised", "credential theft or command manipulation", ("BND-REMOTE-WINRM", "BND-REMOTE-RDP", "BND-CRYPTO-TRANSPORT"), ("TEC-002", "TEC-011")),
    ("TS-108", "Abuse of exposed remote-management interfaces", "remote or network-adjacent attacker", "a management interface is reachable and weakly restricted", "managed hosts", "insufficient remote access boundary", "uses the interface to authenticate or execute commands", "gain administrative control", "unauthorized management access", "remote control or lateral movement", ("BND-REMOTE-WINRM", "BND-REMOTE-RDP"), ("TEC-003", "TEC-004")),
    ("TS-109", "Credential extraction from weak password material", "attacker with access to credential storage", "reversible or legacy password material exists", "stored credentials", "recoverable password representation", "extracts reusable password material", "impersonate an account", "credential theft", "unauthorized authentication", ("BND-IDENTITY-PRIVILEGED-CREDENTIALS",), ("TEC-006",)),
    ("TS-110", "Credential extraction from operating-system memory", "attacker with local code execution", "credential material is exposed to ordinary process access", "credential authority and memory", "missing credential-process isolation", "reads secrets from protected process memory", "obtain privileged credentials", "credential theft", "administrative or domain compromise", ("BND-IDENTITY-PRIVILEGED-CREDENTIALS",), ("TEC-006",)),
    ("TS-111", "Privilege elevation through weak consent enforcement", "attacker with local execution", "elevation is not mediated by an effective consent boundary", "administrative tokens", "weak privileged-execution mediation", "triggers an elevated action", "execute with administrative privileges", "privilege escalation", "host compromise", ("BND-IDENTITY-PRIVILEGED-CREDENTIALS",), ("TEC-007",)),
    ("TS-112", "Malicious code after protection disablement", "attacker with local influence", "host protection can be disabled", "endpoint protection and host", "protection disablement is permitted", "impairs protection and launches code", "persist without prevention", "security protection impaired", "malware execution", ("BND-ENDPOINT-MALWARE-PROTECTION",), ("TEC-009", "TEC-008")),
    ("TS-113", "Malware evasion of endpoint protection", "malicious content reaching a host", "real-time or behavioral prevention is incomplete", "host execution surfaces", "missing continuous prevention", "evades supplemental scanning and executes", "run malicious payloads", "malware execution", "host compromise", ("BND-ENDPOINT-MALWARE-PROTECTION",), ("TEC-008", "TEC-009")),
    ("TS-114", "Unsigned or untrusted code execution", "attacker able to deliver executable content", "execution admission does not enforce trust", "applications and scripts", "missing code trust enforcement", "launches unsigned or untrusted content", "execute attacker-controlled code", "untrusted code execution", "remote or local code execution", ("BND-EXECUTION-APPLICATION-CONTROL", "BND-EXECUTION-SCRIPT-CONTROL"), ("TEC-008",)),
    ("TS-115", "Security-event suppression", "attacker with influence over audit configuration", "essential event generation can be disabled", "security event pipeline", "missing audit enforcement", "suppresses security event creation", "avoid detection", "security activity unobserved", "loss of security visibility", ("BND-MONITORING-SECURITY-AUDIT",), ("TEC-010",)),
    ("TS-116", "Loss of forensic audit evidence", "attacker or failure affecting log retention", "records are not preserved", "audit records", "insufficient evidence retention", "removes or causes loss of records", "prevent investigation", "forensic evidence unavailable", "loss of attribution and investigation capability", ("BND-MONITORING-SECURITY-AUDIT",), ("TEC-010",)),
    ("TS-117", "Plaintext network credential exposure", "attacker on a network path", "credentials traverse an unencrypted channel", "credentials and sessions", "plaintext transport accepted", "captures credential-bearing traffic", "recover reusable credentials", "credential theft", "unauthorized authentication", ("BND-CRYPTO-TRANSPORT", "BND-REMOTE-WINRM"), ("TEC-011", "TEC-002")),
    ("TS-118", "Unencrypted data-at-rest exposure", "attacker with physical or storage access", "stored data lacks cryptographic protection", "persistent data", "missing storage encryption", "reads storage outside normal authorization", "obtain protected data", "unauthorized data access", "loss of confidentiality", ("BND-DATA-STORAGE-ENCRYPTION",), ("TEC-012",)),
)

THREAT_SCENARIOS = tuple(
    ThreatScenario(
        threat_scenario_id=row[0], name=row[1],
        description=f"{row[1]} is a concrete adversarial situation independent of any source benchmark.",
        attacker_position=row[2], preconditions=(row[3],), targeted_assets=(row[4],),
        abused_weakness=row[5], attacker_action=row[6], attacker_objective=row[7],
        immediate_outcome=row[8], technical_impact=row[9], boundary_ids=row[10],
        technique_ids=row[11],
        evidence=(CuratedEvidence(source="security architecture catalog", locator=row[0], assertion=f"The described weakness enables {row[1].lower()}.", confidence="High"),),
        provenance=PROVENANCE,
    )
    for row in _SCENARIOS
)
