class Page:
    def get_text(self, option: str) -> str: ...
    def insert_text(
        self, point: tuple[int, int], text: str, *, fontsize: int = ...
    ) -> None: ...


class Document:
    page_count: int

    def load_page(self, page_id: int) -> Page: ...
    def new_page(self) -> Page: ...
    def save(self, filename: str) -> None: ...
    def close(self) -> None: ...


def open(filename: str | None = None) -> Document: ...
