from __future__ import annotations

from .schema import AttackPath

ATTACK_PATHS = (
    AttackPath(attack_path_id="AP-001", name="Credential relay and authentication interception", description="An attacker intercepts or relays authentication exchanges to impersonate a trusted identity.", stages=["credential access", "authentication", "lateral movement"], affected_assets=["identity providers", "network services", "credentials"], security_outcomes=["authentication integrity", "identity assurance"], mitre_technique_ids=["T1557", "T1550"]),
    AttackPath(attack_path_id="AP-002", name="Credential extraction from operating-system memory", description="An attacker with local execution reads credential secrets or derivatives from protected operating-system processes.", stages=["execution", "privilege escalation", "credential access"], affected_assets=["operating-system memory", "credential authority", "administrative credentials"], security_outcomes=["credential confidentiality"], mitre_technique_ids=["T1003"]),
    AttackPath(attack_path_id="AP-003", name="Lateral movement over administrative protocols", description="An attacker uses an administrative network protocol to move from one system to another.", stages=["authentication", "lateral movement"], affected_assets=["managed hosts", "administrative protocols"], security_outcomes=["network containment", "administrative access control"], mitre_technique_ids=["T1021"]),
    AttackPath(attack_path_id="AP-004", name="Abuse of remote-management interfaces", description="An attacker reaches or misuses a remote administration interface to control a system.", stages=["initial access", "authentication", "execution"], affected_assets=["remote management services", "managed hosts"], security_outcomes=["secure administration"], mitre_technique_ids=["T1021"]),
    AttackPath(attack_path_id="AP-005", name="Malicious code and script execution", description="Untrusted executable content reaches an execution surface and runs on the system.", stages=["delivery", "execution"], affected_assets=["applications", "scripts", "host processes"], security_outcomes=["execution integrity"], mitre_technique_ids=["T1059", "T1204"]),
    AttackPath(attack_path_id="AP-006", name="Malware evasion and protection disablement", description="Malware evades behavioral prevention or disables protection so malicious activity can persist.", stages=["defense evasion", "persistence", "impact"], affected_assets=["malware protection stack", "host"], security_outcomes=["continuous prevention", "malware containment"], mitre_technique_ids=["T1562.001"]),
    AttackPath(attack_path_id="AP-007", name="Unauthorized inbound network access", description="Unsolicited or unauthorized network traffic crosses the host boundary and reaches a service.", stages=["reconnaissance", "initial access"], affected_assets=["host network boundary", "listening services"], security_outcomes=["network access restriction"], mitre_technique_ids=[]),
    AttackPath(attack_path_id="AP-008", name="Privilege elevation through weak consent boundaries", description="Code obtains administrative execution through absent, bypassable, or spoofable elevation consent.", stages=["execution", "privilege escalation"], affected_assets=["administrative tokens", "elevation interface"], security_outcomes=["privileged execution mediation"], mitre_technique_ids=["T1548.002"]),
    AttackPath(attack_path_id="AP-009", name="Plaintext or weakly protected credential storage", description="Reusable credentials or weak derivatives remain recoverable from storage or delegated state.", stages=["credential access", "collection"], affected_assets=["credential stores", "delegated credentials", "password derivatives"], security_outcomes=["credential confidentiality"], mitre_technique_ids=["T1552"]),
    AttackPath(attack_path_id="AP-010", name="Security-event suppression or loss of forensic evidence", description="Relevant security activity is not recorded or retained, preventing detection or investigation.", stages=["defense evasion", "detection", "investigation"], affected_assets=["security logs", "audit pipeline"], security_outcomes=["security visibility", "forensic integrity"], mitre_technique_ids=["T1070"]),
)

ATTACK_PATH_BY_ID = {item.attack_path_id: item for item in ATTACK_PATHS}

